// Flat ESLint config. Deliberately tuned for an existing large codebase: it
// errors only on genuine bug patterns (hook misuse, reassigned functions, bad
// typeof, etc.) and treats stylistic / hygiene findings as warnings or off, so
// the gate is adoptable without a thousand-line churn. `npm run lint` enforces a
// warning ceiling (--max-warnings); ratchet it down over time.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
  {
    // Only lint hand-written source; skip build output, vendored, and generated.
    ignores: [
      'node_modules/**',
      'dist/**',
      'dist-server/**',
      'dist-electron/**',
      'dist-installer/**',
      'deploy/**', // bundled/minified web assets, not source
      'build/**',
      'public/**',
      'screenshots/**',
      'preview-shots/**',
      'ds-bundle/**',
      'ai-service/**',
      'src-tauri/**',
      'tools/**',
      'scripts/**',
      'migrations/**',
      'tests/**',
      '**/*.config.js',
      '**/*.config.ts',
      '**/*.cjs',
      '**/*.mjs',
      'src/icons/index.tsx', // generated by scripts/gen-fiori-icons.mjs
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Final, unscoped override so it wins over the recommended presets for every
  // linted file. Globals declared here so core no-undef-style rules (when on)
  // recognise browser + node environments.
  {
    plugins: { 'react-hooks': reactHooks },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.browser, ...globals.node },
    },
    rules: {
      // ── Real-bug rules: errors ──
      'react-hooks/rules-of-hooks': 'error',
      'no-debugger': 'error',
      'no-func-assign': 'error',
      'valid-typeof': 'error',
      'getter-return': 'error',
      'no-dupe-keys': 'error',
      'no-misleading-character-class': 'error',
      'no-sparse-arrays': 'error',

      // ── Hygiene: warn (visible, non-blocking baseline) ──
      'react-hooks/exhaustive-deps': 'warn',
      'prefer-const': 'warn',
      'no-cond-assign': ['warn', 'except-parens'],
      'no-fallthrough': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', ignoreRestSiblings: true },
      ],

      // ── Intentional patterns / TS-handled: off ──
      // `cond && fn()` and `a?.b()` expression-statements are used throughout.
      'no-unused-expressions': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      // TypeScript already resolves identifiers; core no-undef is redundant noise.
      'no-undef': 'off',
      // `any` is pervasive (guarded require('electron'), sql.js rows, IPC args).
      '@typescript-eslint/no-explicit-any': 'off',
      // Guarded CommonJS require() is the established cross-shell interop pattern.
      '@typescript-eslint/no-require-imports': 'off',
      'no-empty': 'off', // `catch {}` swallow-and-continue is used deliberately
      'no-prototype-builtins': 'off',
      'no-constant-condition': 'off', // while(true) worker loops
      'no-useless-escape': 'off',
      'no-control-regex': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-this-alias': 'off',
      'no-console': 'off', // console is intentional on the server and dev paths
    },
  },
);
