@echo off
title Promix — Publicare Update Electron
color 0A

echo ============================================
echo   PROMIX AUTOMATIX — Publicare Update
echo ============================================
echo.

:: Config
set UPDATES_DIR=C:\PromixData\updates
set BUILD_DIR=%~dp0..\release
set PACKAGE_JSON=%~dp0..\package.json

:: Extract version from package.json
for /f "tokens=2 delims=:, " %%a in ('findstr /c:"\"version\"" "%PACKAGE_JSON%"') do set RAW_VER=%%a
set VERSION=%RAW_VER: =%
set VERSION=%VERSION:"=%
echo   Versiune: %VERSION%

:: Create updates dir
if not exist "%UPDATES_DIR%" mkdir "%UPDATES_DIR%"

:: Find NSIS installer (or MSI)
set INSTALLER=
for %%f in ("%BUILD_DIR%\*.exe") do set INSTALLER=%%f
if "%INSTALLER%"=="" (
  for %%f in ("%BUILD_DIR%\*.msi") do set INSTALLER=%%f
)
if "%INSTALLER%"=="" (
  echo [EROARE] Nu gasesc installer in %BUILD_DIR%\
  echo Ruleaza mai intai: npm run build:electron
  pause
  exit /b 1
)
echo   Installer: %INSTALLER%

:: Get local IP
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /i "IPv4"') do set LOCALIP=%%a
set LOCALIP=%LOCALIP: =%
echo   IP: %LOCALIP%

:: Copy installer to updates dir
echo.
echo [1/3] Copiez installer...
copy /Y "%INSTALLER%" "%UPDATES_DIR%\" >nul
for %%f in ("%INSTALLER%") do set INSTALLER_NAME=%%~nxf
echo       %INSTALLER_NAME%

:: Check if latest.yml exists (generated by electron-builder with publish config)
set YML_SRC=%BUILD_DIR%\latest.yml
if exist "%YML_SRC%" (
  echo [2/3] Copiez latest.yml generat de electron-builder...
  copy /Y "%YML_SRC%" "%UPDATES_DIR%\latest.yml" >nul
  echo       latest.yml copiat
) else (
  echo [2/3] latest.yml nu exista -- genereaza cu: npm run build:electron
  echo       Atentie: fara latest.yml auto-updaterul nu functioneaza
)

echo [3/3] Verificare...
echo.
if exist "%UPDATES_DIR%\latest.yml" (
  type "%UPDATES_DIR%\latest.yml"
)
echo.
echo ============================================
echo   UPDATE PUBLICAT!
echo ============================================
echo.
echo   Versiune:  %VERSION%
echo   Installer: %UPDATES_DIR%\%INSTALLER_NAME%
echo   URL check: http://%LOCALIP%:3500/api/update/latest.yml
echo.
echo   Clientii cu versiune mai veche vor primi
echo   notificare de update automat.
echo ============================================
pause
