# AUTOGENERATED by scripts/install-autostart.ps1 â€” DO NOT EDIT BY HAND.
# Re-run install-autostart.ps1 to regenerate after moving the project.
$ErrorActionPreference = 'Continue'
$env:PATH = 'C:\Program Files\nodejs;' + $env:PATH
Set-Location -Path 'C:\APLICATIE AUTOMATIX\Automatix-NEW'
& 'C:\APLICATIE AUTOMATIX\Automatix-NEW\scripts\automatix-launcher.ps1'
