# AUTOGENERATED by scripts/install-autostart.ps1 â€” DO NOT EDIT BY HAND.
# Logon fallback: start the server ONLY if the boot task hasn't already.
$ErrorActionPreference = 'Continue'
try {
  $r = Invoke-WebRequest -Uri 'http://127.0.0.1:3500/api/health' -UseBasicParsing -TimeoutSec 4
  if ($r.StatusCode -eq 200) { exit 0 }  # already up (boot task) â€” do nothing
} catch { }
$env:PATH = 'C:\Program Files\nodejs;' + $env:PATH
Set-Location -Path 'C:\APLICATIE AUTOMATIX\Automatix-NEW'
& 'C:\APLICATIE AUTOMATIX\Automatix-NEW\scripts\automatix-launcher.ps1'
