# =============================================================================
# install-autostart.ps1
#
# Registers a Windows Task Scheduler entry that auto-starts the Automatix
# server when the PC boots, even before any user logs in. Survives:
#   - power cuts (UPS or no UPS — task fires next boot)
#   - Windows updates that reboot the machine
#   - the user not being signed in (RDP / remote installs)
#
# Run ONCE, as Administrator. Subsequent boots auto-start.
#
# Uninstall: scripts/uninstall-autostart.ps1
# Manual trigger now (no reboot needed):
#   Start-ScheduledTask -TaskName 'Automatix Server Autostart'
# Inspect:
#   Get-ScheduledTask -TaskName 'Automatix Server Autostart' | Get-ScheduledTaskInfo
# =============================================================================

$ErrorActionPreference = 'Stop'
$TaskName    = 'Automatix Server Autostart'
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$Launcher    = Join-Path $ProjectRoot 'scripts\automatix-launcher.ps1'
$WrapperPs1  = Join-Path $ProjectRoot 'scripts\_autostart-wrapper.ps1'
$GuardPs1    = Join-Path $ProjectRoot 'scripts\_autostart-login-guard.ps1'

# ----------------------------------------------------------------------------
# Pre-flight: must run as Administrator
# ----------------------------------------------------------------------------
$me = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
if (-not $me.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host ''
    Write-Host '[!] Acest script trebuie rulat ca Administrator.' -ForegroundColor Red
    Write-Host '    Reincerc cu UAC...' -ForegroundColor Yellow
    Start-Process powershell -Verb RunAs -ArgumentList @(
        '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $PSCommandPath
    )
    exit 0
}

Write-Host ''
Write-Host '===============================================================' -ForegroundColor Cyan
Write-Host '  Automatix — instalare auto-start la pornire Windows' -ForegroundColor Cyan
Write-Host '===============================================================' -ForegroundColor Cyan
Write-Host ''

# ----------------------------------------------------------------------------
# Sanity checks on the paths we'll bake into the task
# ----------------------------------------------------------------------------
if (-not (Test-Path $Launcher)) {
    Write-Host "[!] Nu gasesc launcher-ul la: $Launcher" -ForegroundColor Red
    exit 1
}
Write-Host "[ok] Project root: $ProjectRoot" -ForegroundColor Green
Write-Host "[ok] Launcher:     $Launcher" -ForegroundColor Green

# Detect Node so we can hard-code its path into the wrapper PATH. SYSTEM
# inherits the system-wide PATH, but if Node was ever installed "current
# user only", SYSTEM wouldn't see it. Pinning the absolute path means we
# don't depend on whatever PATH SYSTEM happens to have.
$NodeExe = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $NodeExe) {
    Write-Host '[!] Nu am gasit node.exe in PATH. Instaleaza Node sau ruleaza-l manual din admin.' -ForegroundColor Red
    exit 1
}
$NodeDir = Split-Path -Parent $NodeExe
Write-Host "[ok] Node:         $NodeExe" -ForegroundColor Green

# ----------------------------------------------------------------------------
# Generate a thin wrapper script that:
#   1. Sets PATH to include Node's directory (so the launcher's `node` works)
#   2. cd's into the project root (so the launcher's relative paths work)
#   3. Invokes the launcher
# The wrapper is regenerated on every install so PATH/project-root changes
# get picked up automatically.
# ----------------------------------------------------------------------------
$wrapperContent = @"
# AUTOGENERATED by scripts/install-autostart.ps1 — DO NOT EDIT BY HAND.
# Re-run install-autostart.ps1 to regenerate after moving the project.
`$ErrorActionPreference = 'Continue'
`$env:PATH = '$NodeDir;' + `$env:PATH
Set-Location -Path '$ProjectRoot'
& '$Launcher'
"@
Set-Content -Path $WrapperPs1 -Value $wrapperContent -Encoding UTF8
Write-Host "[ok] Wrapper generat: $WrapperPs1" -ForegroundColor Green

# ----------------------------------------------------------------------------
# Login-path GUARD.
#
# The boot scheduled task runs as SYSTEM. The registry Run key (below) fires
# at user logon as the *user* (non-admin). If the boot task already started
# the server, a plain logon launch would:
#   - fail to bind :3500 (node exits) AND
#   - spawn a SECOND cloudflared on the same tunnel (the user can't kill the
#     SYSTEM-owned one, so the launcher's "stop previous" step is denied).
# The guard checks health first and exits early if the server is already up,
# so the logon path is a true no-op when the boot task did its job.
# ----------------------------------------------------------------------------
$guardContent = @"
# AUTOGENERATED by scripts/install-autostart.ps1 — DO NOT EDIT BY HAND.
# Logon fallback: start the server ONLY if the boot task hasn't already.
`$ErrorActionPreference = 'Continue'
try {
  `$r = Invoke-WebRequest -Uri 'http://127.0.0.1:3500/api/health' -UseBasicParsing -TimeoutSec 4
  if (`$r.StatusCode -eq 200) { exit 0 }  # already up (boot task) — do nothing
} catch { }
`$env:PATH = '$NodeDir;' + `$env:PATH
Set-Location -Path '$ProjectRoot'
& '$Launcher'
"@
Set-Content -Path $GuardPs1 -Value $guardContent -Encoding UTF8
Write-Host "[ok] Guard logon generat: $GuardPs1" -ForegroundColor Green

# ----------------------------------------------------------------------------
# Drop any previous registration so re-runs are idempotent
# ----------------------------------------------------------------------------
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Write-Host "[..] Sterg task-ul existent..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

# ----------------------------------------------------------------------------
# Build the Task Scheduler entry
# ----------------------------------------------------------------------------
$action = New-ScheduledTaskAction `
    -Execute 'powershell.exe' `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$WrapperPs1`"" `
    -WorkingDirectory $ProjectRoot

# Trigger: at system startup with 60s delay so DHCP / DNS / network adapters
# are fully up before we try to bind :3500 and open the cloudflare tunnel.
$trigger = New-ScheduledTaskTrigger -AtStartup
$trigger.Delay = 'PT1M'

# Settings tuned for a long-lived background service.
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1) `
    -MultipleInstances IgnoreNew

# Run as SYSTEM with elevated rights. No password to store, no user has to
# be logged in. SYSTEM has full read access to the project directory and
# can bind privileged ports if needed (we use 3500, so we don't strictly
# need this, but it future-proofs).
$principal = New-ScheduledTaskPrincipal `
    -UserId 'SYSTEM' `
    -LogonType ServiceAccount `
    -RunLevel Highest

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description 'Auto-start Automatix server (node + ai-service + cloudflared) la pornirea Windows. Generat de scripts/install-autostart.ps1.' | Out-Null

# ----------------------------------------------------------------------------
# Backup mechanism: HKLM\...\Run key.
#
# Why: Windows feature updates (10 → 11, 22H2 → 24H2, etc.) sometimes
# wipe non-built-in scheduled tasks. This actually happened during this
# install — Windows Update silently deleted the task, leaving the user
# without auto-start on next boot. Registry Run keys survive feature
# updates much better than scheduled tasks because they're considered
# core OS state.
#
# Trade-off: Run keys fire at user logon (not at boot like the scheduled
# task), so the service starts ~5-10 seconds after the user reaches the
# desktop instead of before login. Combined with the scheduled task as
# primary, this means:
#   - Normal boot: scheduled task starts the server pre-login (fastest)
#   - After feature update wipes the task: Run key still fires on first
#     login, server starts a few seconds late but works
#
# The launcher's own first step is to kill any existing server instance,
# so if both fire (task ran AND user logs in), no duplicate processes.
# ----------------------------------------------------------------------------
$runKeyPath = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Run'
$runKeyName = 'AutomatixServerAutostart'
$runKeyValue = "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$GuardPs1`""
Set-ItemProperty -Path $runKeyPath -Name $runKeyName -Value $runKeyValue -Force
Write-Host "[ok] Backup in registry: $runKeyPath\$runKeyName" -ForegroundColor Green

Write-Host ''
Write-Host '===============================================================' -ForegroundColor Green
Write-Host '  [OK] Auto-start inregistrat cu DOUA mecanisme!' -ForegroundColor Green
Write-Host '===============================================================' -ForegroundColor Green
Write-Host ''
Write-Host '  PRIMAR (Task Scheduler):'
Write-Host "    Nume task:    $TaskName"
Write-Host "    Trigger:      la pornirea Windows (1 minut delay pt. retea)"
Write-Host '    Ruleaza ca:   SYSTEM (nu necesita login utilizator)'
Write-Host '    Pe baterie:   permis'
Write-Host '    Restart:      3 incercari la 1 minut interval daca esueaza'
Write-Host ''
Write-Host '  BACKUP (Registry Run key):'
Write-Host "    Cheie:        HKLM:\\...\\Run\\$runKeyName"
Write-Host '    Trigger:      la fiecare login de user (orice cont admin)'
Write-Host '    Rol:          fallback daca Windows Update sterge task-ul'
Write-Host ''
Write-Host 'Verifica statusul oricand:' -ForegroundColor Yellow
Write-Host "  Get-ScheduledTask -TaskName '$TaskName' | Get-ScheduledTaskInfo"
Write-Host ''
Write-Host 'Testeaza acum, fara sa restartezi:' -ForegroundColor Yellow
Write-Host "  Start-ScheduledTask -TaskName '$TaskName'"
Write-Host ''
Write-Host 'Dezinstalare:' -ForegroundColor Yellow
Write-Host '  & "$PSScriptRoot\uninstall-autostart.ps1"'
Write-Host ''
